import { createFreeGlobalMirror } from '../../tools/free-global-mirror.mjs';
import { financeRepository } from '../db/repository';
import { financeDb } from '../db/database';
import type { Instrument, Price } from '../core/types';

export interface MarketInstrument {symbol:string;name:string;currency:string;market?:string;exchange?:string;timeZone?:string;assetType:string;}
export interface MarketQuote extends MarketInstrument {value:number;asOf:string;marketDate?:string;timestampPrecision?:string;source:string;sourceUrl?:string;freshness:string;changePercent?:number;}
export interface PriceProvider {search(query:string,market:string):Promise<MarketInstrument[]>;latestPrice(symbol:string):Promise<MarketQuote>;priceHistory(symbol:string,range:string):Promise<{points:{date:string;close:number|null}[];source:string;currency?:string}>;}
const international=createFreeGlobalMirror({browserCors:true,timeoutMs:20000});
const starters:Record<string,string[]>={US:['US:AAPL','US:MSFT','US:NVDA'],HK:['HK:0700'],JP:['JP:7203'],GB:['GB:VOD'],CA:['CA:SHOP'],AU:['AU:BHP']};
function safeBase(value:string){const u=new URL(value);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['127.0.0.1','localhost'].includes(u.hostname)))throw new Error('Use an HTTPS gateway URL.');if(u.username||u.password||u.search||u.hash)throw new Error('Use a base URL without credentials.');return u.href.replace(/\/$/,'');}
async function externalResponse(path:string){const configured=await financeRepository.getSetting<string>('marketGateway','');const base=configured?safeBase(configured):['localhost','127.0.0.1'].includes(location.hostname)?'/api/public':'';if(!base)throw new Error('Connect a Philippine gateway in Settings, or enter a manual price.');const response=await fetch(base+path,{signal:AbortSignal.timeout(10000),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('The market source could not return this data. Your last saved prices are kept.');return response.json();}
async function globalResponse(path:string){if(['localhost','127.0.0.1'].includes(location.hostname)){try{return await externalResponse(path);}catch{/* Public daily data also works without a local gateway. */}}const url=new URL(path,'https://local.invalid');if(url.pathname==='/catalog'){const market=url.searchParams.get('market')||'US',query=url.searchParams.get('q')||'',catalog=await international.catalog(market,query);return {...catalog,instruments:query?catalog.instruments:catalog.instruments.filter(i=>(starters[market]||[]).includes(i.symbol))};}if(url.pathname==='/quotes'){const quote=await international.quote(url.searchParams.get('symbols')||'');return {quotes:[quote]};}if(url.pathname.startsWith('/history/'))return international.history(decodeURIComponent(url.pathname.slice(9)),url.searchParams.get('range')||'1m');throw new Error('Unsupported market request.');}
export const marketProvider:PriceProvider={
  async search(query,market){const path=`/catalog${market==='PH'?'':`?market=${market}`}${query?`${market==='PH'?'?':'&'}q=${encodeURIComponent(query)}`:''}`;const data=market==='PH'?await externalResponse(path):await globalResponse(path);return data.instruments||[];},
  async latestPrice(symbol){const path='/quotes?symbols='+encodeURIComponent(symbol),data=symbol.includes(':')?await globalResponse(path):await externalResponse(path);const quote=data.quotes?.find((q:MarketQuote)=>q.symbol===symbol);if(!quote||!Number.isFinite(quote.value)||quote.value<=0||!Number.isFinite(Date.parse(quote.asOf))||Date.parse(quote.asOf)>Date.now()+300000||typeof quote.currency!=='string'||!/^[A-Z]{3}$/.test(quote.currency)||typeof quote.source!=='string'||!quote.source.trim())throw new Error(data.issues?.[0]?.message||'No recent verified quote is available for this ticker.');return quote;},
  async priceHistory(symbol,range){const path='/history/'+encodeURIComponent(symbol)+'?range='+encodeURIComponent(range);return symbol.includes(':')?globalResponse(path):externalResponse(path);},
};
export async function refreshInstrumentPrice(instrument:Instrument){if(!instrument.sourceSymbol&&!instrument.symbol)throw new Error('Add a provider ticker to this instrument first.');const quote=await marketProvider.latestPrice(instrument.sourceSymbol||instrument.symbol!);if(quote.currency!==instrument.currency)throw new Error('The source currency differs from this instrument. Verify its price unit before saving.');const existing=await financeRepository.getSetting('priceRefreshErrors',{} as Record<string,string>);const date=new Date().toISOString();const price:Price={id:crypto.randomUUID(),instrumentId:instrument.id,value:quote.value,currency:quote.currency,asOf:quote.asOf,fetchedAt:date,source:quote.source,sourceSymbol:quote.symbol,staleAfter:new Date(Date.parse(quote.asOf)+3*86400000).toISOString(),status:Date.now()-Date.parse(quote.asOf)>3*86400000?'stale':'fresh'};await financeRepository.save('prices',price);delete existing[instrument.id];await financeRepository.setSetting('priceRefreshErrors',existing);return price;}
export async function refreshFx(base='PHP'){
  if(!/^[A-Z]{3}$/.test(base))throw new Error('Choose a valid base currency.');
  const cached=await financeRepository.getSetting<{count:number;asOf:string;fetchedAt:number}>('fx-refresh:'+base);if(cached&&Date.now()-cached.fetchedAt<3600000)return {count:cached.count,asOf:cached.asOf};
  const response=await fetch(`https://open.er-api.com/v6/latest/${base}`,{signal:AbortSignal.timeout(12000)});const data=await response.json();if(!response.ok||data.result!=='success'||data.base_code!==base||!Number.isSafeInteger(data.time_last_update_unix)||data.time_last_update_unix*1000>Date.now()+300000||!data.rates||data.rates[base]!==1)throw new Error('The free FX source is unavailable or invalid. Saved rates are kept.');
  const asOf=new Date(data.time_last_update_unix*1000).toISOString();let count=0;
  await financeDb.transaction('rw',financeDb.tables,async()=>{for(const currency of ['PHP','USD','EUR','GBP','JPY','HKD','CAD','AUD','SGD']){const rate=data.rates[currency];if(currency===base||typeof rate!=='number'||!Number.isFinite(rate)||rate<=0)continue;await financeRepository.save('fxRates',{id:`fx:${currency}:${base}:${asOf}`,fromCurrency:currency,toCurrency:base,rate:1/rate,asOf,source:'ExchangeRate-API open daily reference',fetchedAt:new Date().toISOString()});count++;}await financeRepository.setSetting('fx-refresh:'+base,{count,asOf,fetchedAt:Date.now()});});return {count,asOf};
}
